### ISSUE TITLE
Error while running locally on windows

### ISSUE THREAD

**Issue by saurabhsensai** [AAitorG/UNETR_2D#1]
When running on windows locally it is giving error as "The last dimension of the inputs to `Dense` should be defined. Found `None`."
Its working fine on Google Colab. 

The error in file unetr_2d.py on line "encoded_patches = PatchEncoder(num_patches, projection_dim)(patches)"

**Comment by AAitorG** [comment]
Hi @saurabhsensai,

Thank you for reaching out and reporting this issue. It sounds like the TensorFlow version could indeed be the culprit here. Since it's working on Colab (with TensorFlow v2.15.0), ensuring you're using the same version locally might resolve the issue.

**Comment by saurabhsensai** [comment]
Great 😃. It actually solved the problem. Thank you very much.

**Comment by AAitorG** [comment]
You're welcome! I'm glad to hear that the solution worked for you.
